export const OTCPairABI = [
  {
    inputs: [
      { name: "_token0", type: "address" },
      { name: "_token1", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "ExceedsRemaining", type: "error" },
  { inputs: [], name: "InvalidActiveIndex", type: "error" },
  { inputs: [], name: "NotMaker", type: "error" },
  { inputs: [], name: "OrderNotActive", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  { inputs: [], name: "ZeroCost", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "orderId", type: "uint256" },
      { indexed: true, name: "recipient", type: "address" },
    ],
    name: "OrderCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "orderId", type: "uint256" },
      { indexed: true, name: "maker", type: "address" },
      { indexed: false, name: "sellToken0", type: "bool" },
      { indexed: false, name: "sellAmount", type: "uint256" },
      { indexed: false, name: "buyAmount", type: "uint256" },
    ],
    name: "OrderCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "orderId", type: "uint256" },
      { indexed: true, name: "taker", type: "address" },
      { indexed: false, name: "sellAmountOut", type: "uint256" },
      { indexed: false, name: "buyAmountDelivered", type: "uint256" },
    ],
    name: "OrderFilled",
    type: "event",
  },
  {
    inputs: [{ name: "orderId", type: "uint256" }],
    name: "cancelOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "recipient", type: "address" },
    ],
    name: "cancelOrderTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "sellToken0_", type: "bool" },
      { name: "sellAmount", type: "uint256" },
      { name: "buyAmount", type: "uint256" },
    ],
    name: "createOrder",
    outputs: [{ name: "orderId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "orderId", type: "uint256" },
      { name: "sellAmountOut", type: "uint256" },
    ],
    name: "fillOrder",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveOrderCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    name: "getActiveOrders",
    outputs: [
      { name: "ids", type: "uint256[]" },
      {
        components: [
          { name: "maker", type: "address" },
          { name: "sellToken0", type: "bool" },
          { name: "sellAmount", type: "uint256" },
          { name: "buyAmount", type: "uint256" },
          { name: "filledSellAmount", type: "uint256" },
          { name: "status", type: "uint8" },
        ],
        name: "result",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "orderId", type: "uint256" }],
    name: "getOrder",
    outputs: [
      {
        components: [
          { name: "maker", type: "address" },
          { name: "sellToken0", type: "bool" },
          { name: "sellAmount", type: "uint256" },
          { name: "buyAmount", type: "uint256" },
          { name: "filledSellAmount", type: "uint256" },
          { name: "status", type: "uint8" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOrderCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "maker", type: "address" },
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    name: "getMakerOrders",
    outputs: [
      { name: "ids", type: "uint256[]" },
      {
        components: [
          { name: "maker", type: "address" },
          { name: "sellToken0", type: "bool" },
          { name: "sellAmount", type: "uint256" },
          { name: "buyAmount", type: "uint256" },
          { name: "filledSellAmount", type: "uint256" },
          { name: "status", type: "uint8" },
        ],
        name: "result",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "maker", type: "address" }],
    name: "getMakerOrderCount",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const
